-- Baseline matching the schema Hibernate's ddl-auto=update already produced for
-- user/User.java, connection/Connection.java, and friend/Friend.java. Applied via
-- Flyway's baseline-on-migrate against existing dev DBs (recorded, not re-run);
-- run for real against a fresh (e.g. prod) DB.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL UNIQUE,
    email varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    first_name varchar(255),
    last_name varchar(255),
    rank varchar(255),
    region varchar(255)
);

CREATE TABLE connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id bigint NOT NULL REFERENCES users (id),
    user2_id bigint NOT NULL REFERENCES users (id),
    connected_at timestamp(6) NOT NULL,
    blocked_by_id bigint REFERENCES users (id)
);

CREATE TABLE friends (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id bigint NOT NULL REFERENCES users (id),
    user2_id bigint NOT NULL REFERENCES users (id),
    status varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL
);
